name = "textbook-annotator"
compatibility_date = "2026-07-29"

[assets]
directory = "./public"

[[kv_namespaces]]
binding = "ANNOTATION_KV"
id = "REPLACE_WITH_PRODUCTION_KV_NAMESPACE_ID"
preview_id = "REPLACE_WITH_PREVIEW_KV_NAMESPACE_ID"